apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  # These values are replaced on cluster creation by workflow
  clusterName: b57dec14-e535-4758-9af6-8ed4ade0e4cd
charts:
- name: cluster-api-byoh
  override:
    cluster.name: $(clusterName)
    machineDeployment:
    - name: tks
      replicas: 1
      selector:
        matchLabels:
          role: tks
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    - name: normal
      replicas: 1
      autoscaling:
        minSize: 1
        maxSize: 5
      selector:
        matchLabels:
          role: worker
